//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.SalesItem = new HashSet<SalesItem>();
        }
    
        public int Id { get; set; }
        public double dateOfTransaction { get; set; }
        public decimal subtotalAmount { get; set; }
        public decimal taxAmount { get; set; }
        public decimal totalPriceAmount { get; set; }
        public decimal totalDiscountAmount { get; set; }
        public decimal moneyPaid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesItem> SalesItem { get; set; }
    }
}
