//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScannerSampleLab1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> QTY { get; set; }
    }
}
